package Exceçao2;

import java.util.Scanner;

public class Finally {

public static void main(String[] args) {
    
    Scanner entrada = new Scanner(System.in);	
		
	try {
		System.out.println(7 / entrada.nextInt());
	}catch (Exception e) {  //tratando de forma generica 
		System.out.println(e.getMessage());
	}finally {       ////forçar que algo seja executado independente de ter erro ou nao 	
		System.out.println("Finalmente..."); //em todas as situaçoes o finally é chamado
		entrada.close();
	}
		
	System.out.println("Fim");	
		
		
		















































































































}





























































}